name: memory_info
description: Flutter package to get device memory info(ram&rom) at android/ios devices
repository: https://github.com/MrOlolo/memory_info/tree/master/memory_info
version: 0.1.0

environment:
  sdk: '>=3.9.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  memory_info_platform_interface: ^0.1.0
    #path: ../memory_info_platform_interface

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  plugin:
    platforms:
      android:
        package: com.mrololo.memory_info
        pluginClass: MemoryInfoPlugin
      ios:
        pluginClass: MemoryInfoPlugin
