name: memory_info_platform_interface
description: A common platform interface for memory_info.
repository: https://github.com/MrOlolo/memory_info/tree/master/memory_info_platform_interface
version: 0.1.0

environment:
  sdk: '>=3.9.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  meta: ^1.17.0
  plugin_platform_interface: ^2.1.8

dev_dependencies:
  flutter_test:
    sdk: flutter